export const navItems = [
  { group: 'MAIN', id: 'dashboard', label: 'Dashboard', href: '#/dashboard', icon: 'DB' },
  { group: 'MEMBERSHIP', id: 'members', label: 'Members / KYC', href: '#/members', icon: 'KY' },
  { group: 'MEMBERSHIP', id: 'capital-savings', label: 'Capital & Savings', href: '#/capital-savings', icon: 'CS' },
  { group: 'LOANS', id: 'applications', label: 'Loan Applications', href: '#/loan-applications', icon: 'LA' },
  { group: 'LOANS', id: 'active-loans', label: 'Active Loans', href: '#/active-loans', icon: 'AL' },
  { group: 'LOANS', id: 'delinquent-loans', label: 'Delinquent Loans', href: '#/delinquent-loans', icon: 'DL' },
  { group: 'LOANS', id: 'payments', label: 'Payments', href: '#/payments', icon: 'PM' },
  { group: 'FINANCIAL', id: 'time-deposits', label: 'Time Deposits', href: '#/time-deposits', icon: 'TD' },
  { group: 'FINANCIAL', id: 'dividends', label: 'Dividends', href: '#/dividends', icon: 'DV' },
  { group: 'FINANCIAL', id: 'patronage', label: 'Patronage', href: '#/patronage', icon: 'PG' },
  { group: 'FINANCIAL', id: 'expenses', label: 'Expenses', href: '#/expenses', icon: 'EX' },
  { group: 'FINANCIAL', id: 'financial-statements', label: 'Financial Statements', href: '#/financial-statements', icon: 'FS' },
  { group: 'REPORTS AND DOCUMENTS', id: 'bir-registry', label: 'BIR Tax-Exempt Registry', href: '#/bir-registry', icon: 'BR' },
  { group: 'REPORTS AND DOCUMENTS', id: 'reports', label: 'Reports', href: '#/reports', icon: 'RP' },
  { group: 'REPORTS AND DOCUMENTS', id: 'forms-printables', label: 'Forms & Printables', href: '#/forms-printables', icon: 'FP' },
  { group: 'SYSTEM', id: 'settings', label: 'Settings', href: '#/settings', icon: 'ST' },
];

export const defaultTheme = {
  primary: '#237a3b',
  secondary: '#1f6f9e',
  accent: '#d99a22',
  background: '#f4f7f5',
  surface: '#ffffff',
  text: '#1d2b24',
  sidebar: '#173f2a',
  button: '#237a3b',
  border: '#d8e0da',
  success: '#237a3b',
  warning: '#b36b00',
  danger: '#b42318',
  chartPalette: '#237a3b,#1f6f9e,#d99a22,#7c3aed,#0f8b8d,#b42318',
};

export const themePresets = [
  {
    name: 'SACADA Default',
    theme: defaultTheme,
  },
  {
    name: 'Blue Office',
    theme: {
      primary: '#1f5f99',
      secondary: '#2f80c0',
      accent: '#d39b2a',
      background: '#f3f7fb',
      surface: '#ffffff',
      text: '#1e2b36',
      sidebar: '#173a59',
      button: '#1f5f99',
      border: '#d5e0eb',
      success: '#1f7a45',
      warning: '#a76200',
      danger: '#b42318',
      chartPalette: '#1f5f99,#2f80c0,#d39b2a,#6941c6,#0f8b8d,#b42318',
    },
  },
  {
    name: 'Green Cooperative',
    theme: {
      primary: '#2f7d32',
      secondary: '#4f8f54',
      accent: '#c8942c',
      background: '#f5f8f1',
      surface: '#ffffff',
      text: '#243123',
      sidebar: '#214f2c',
      button: '#2f7d32',
      border: '#d6e2d1',
      success: '#2f7d32',
      warning: '#a76200',
      danger: '#b42318',
      chartPalette: '#2f7d32,#6a994e,#c8942c,#386641,#0f8b8d,#b42318',
    },
  },
  {
    name: 'High Contrast',
    theme: {
      primary: '#005a32',
      secondary: '#004c8c',
      accent: '#b85c00',
      background: '#ffffff',
      surface: '#ffffff',
      text: '#111111',
      sidebar: '#111111',
      button: '#005a32',
      border: '#111111',
      success: '#005a32',
      warning: '#8a4a00',
      danger: '#9b1c1c',
      chartPalette: '#005a32,#004c8c,#b85c00,#111111,#666666,#9b1c1c',
    },
  },
  {
    name: 'Light Minimal',
    theme: {
      primary: '#376c55',
      secondary: '#5b7891',
      accent: '#a87628',
      background: '#fafafa',
      surface: '#ffffff',
      text: '#24302a',
      sidebar: '#33423a',
      button: '#376c55',
      border: '#d9dedb',
      success: '#376c55',
      warning: '#9b650f',
      danger: '#a33a32',
      chartPalette: '#376c55,#5b7891,#a87628,#7d6b91,#3d7f7c,#a33a32',
    },
  },
];

export const members = [];
export const loanApplications = [];
export const activeLoans = [];
export const payments = [];

export const reportTypes = [
  'Registry of Members',
  'Membership by Type',
  'Capital Subscription',
  'Paid-Up Share Capital',
  'Regular Savings',
  'Members by Barangay',
  'Members by Sex',
  'Members by Civil Status',
  'Members by Age Group',
  'Members by Profession',
  'Members by Education',
  'Members by Income Classification',
  'Members by Specialization',
  'Loan Register',
  'Loan Releases',
  'Loan Payments',
  'Loan Receivables',
  'Delinquent Loans',
  'Penalties',
  'Processing Fees',
  'Collection Target vs Actual',
  'Statement of Account',
  'Expenses',
  'Time Deposits',
  'Dividends',
  'Patronage',
  'Statement of Financial Position',
  'Statement of Operations',
  'Net Surplus Allocation',
  'Statement of Cash Flows',
  'Financial Status Summary',
  'BIR Tax-Exempt Registry',
  'Member Registry as of Date',
  'Capital Share Report',
];

export const requirementItems = [
  'Membership Form Completed',
  'Loan Application Form Completed',
  'Valid ID Submitted',
  'TIN Number Provided',
  'PMES Completed',
  'Membership Fee Paid',
  'At least PHP 2,000 Share Capital',
  'Savings Deposit',
  'Time Deposit',
  'Co-maker Confirmed',
  'Employment Certification Submitted',
  'Salary Deduction Agreement Signed',
  'Data Privacy Consent Signed',
  'Promissory Note Signed',
  'DTI Registration, if self-employed',
  "Mayor's Permit, if self-employed",
  'Other Supporting Documents',
];
